//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDWebPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class T_NewsMasters
    {
        public int NewsID { get; set; }
        public int NewsSubCategoryID { get; set; }
        public string Heading { get; set; }
        public string SubHeading { get; set; }
        [AllowHtml]
        public string BodyMessage { get; set; }
        public string VideoLink { get; set; }
        public string Remarks { get; set; }
        public string Location { get; set; }
        public int NoOfViews { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public int NewsType { get; set; }
    
        public virtual M_SubCategoryMaster M_SubCategoryMaster { get; set; }
        public virtual M_Master M_Master { get; set; }
    }
}
